# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'RegisterACO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RegisterACO
  pod 'Alamofire', '~> 5.4'
  pod 'SDWebImage', '~> 5.0'
  pod 'IQKeyboardManagerSwift'
end
